doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            feature_status: string
            step_extra_param_type: string
            step_part_type: string
            step_part_strategy: string
            step_type: string
            step_adverb: string
            param_type: string
            project_visibility: string
            scenario_type: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
