nelmio_api_doc:
    documentation:
        info:
            title: Dentest API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                PullToken:
                    type: apiKey
                    in: header
                    name: Authorization
                    description: Prefix the token with `Pull `.
    areas:
        default:
            path_patterns:
                - ^/(?!(_error|doc(?:\.json)?$)).*
