security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: auto
    providers:
        db:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        pull:
            pattern: ^/pull/
            stateless: true
            custom_authenticators:
                - App\Security\Guard\PullTokenAuthenticator
        api:
            pattern: ^/
            stateless: true
            jwt: ~
    access_control:
        - { path: ^/doc(?:\.json)?$, roles: PUBLIC_ACCESS }
        - { path: ^/pull/, roles: ROLE_PULL }
        - { path: ^/, roles: ROLE_USER, methods: [DELETE, POST, PUT] }
