security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User: auto
    providers:
        db:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_path: username
                password_path: password
        register:
            pattern: ^/register
            stateless: true
        pull:
            pattern: ^/pull/
            stateless: true
            custom_authenticators:
                - App\Security\Guard\PullTokenAuthenticator
        api:
            pattern: ^/
            stateless: true
            jwt: ~
    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password-request, roles: PUBLIC_ACCESS }
        - { path: ^/me/?$, roles: ROLE_USER }
        - { path: ^/pull/, roles: ROLE_PULL }
        - { path: ^/, roles: ROLE_USER, methods: [DELETE, POST, PUT] }
        - { path: ^/organizations/?$, roles: ROLE_USER, methods: [GET] }
